name: main-quality

on:
  push:
    branches: [main]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm run lint:check

      - run: pnpm run format:check

      - run: pnpm run type:check
