name: next-release

on:
  workflow_run:
    workflows: ['stable-release']
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm changeset version --snapshot next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: |
          pnpm build:packages
          pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          pnpm changeset publish --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
