name: pr-quality

on:
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  check-and-fix-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm run lint:fix

      - run: pnpm run format:fix

      - run: pnpm run type:check

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: lint & format fixed'
