name: pr-release

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm build

      - name: Create snapshot version for @pr
        run: pnpm changeset version --snapshot ${{ github.event.pull_request.user.login }}

      - name: NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to @pr
        run: pnpm changeset publish --tag pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
