name: pr-release

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: read
      contents: read
      packages: write
      pull-requests: read
      issues: read

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm build:packages

      - name: Create snapshot version for @dev-only-pr
        run: pnpm changeset version --snapshot dev-only-pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: NPM authentication
      #   run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to @dev-only-pr
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish --tag dev-only-pr
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
