name: pr-release

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Context vars
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Find pr-release comment
        uses: peter-evans/find-comment@v3
        id: pr-fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!--pr-release-->'

      - name: Create or update pr-releasing...comment
        uses: peter-evans/create-or-update-comment@v4
        id: pr-couc
        with:
          comment-id: ${{ steps.pr-fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!--pr-release-->
            PR-release for testing:

            Latest commit: `${{ steps.vars.outputs.short_sha }}`
            Status: 👷 Build in progress...
          edit-mode: replace

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm build:packages

      - run: pnpm changeset version --snapshot dev-pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: NPM registry authentication
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm changeset publish --tag dev-pr

      - name: Get @dinui/react version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        id: dinui-react-version
        with:
          path: packages/react-ui

      - name: Update pr-released comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.pr-couc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!--pr-release-->
            PR-release for testing:

            Latest commit: `${{ steps.vars.outputs.short_sha }}`
            Status: ✅ Published successfully

            ```bash
            npm install @dinui/react@${{ steps.dinui-react-version.outputs.current-version}}
            ```
          edit-mode: replace
