name: stable-release

# on:
#   workflow_run:
#     workflows: ['main-quality']
#     types:
#       - completed

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - run: pnpm i

      - run: pnpm build

      - name: NPM registry authentication
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check changesets on @latest
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy and publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          pnpm dlx wrangler pages deploy --project-name=dinui-stable --branch=main ./apps/web/dist 
          pnpm changeset publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
